baseURL = 'https://lakshbudhrani.github.io/course-notes/'
languageCode = 'en-us'
title = 'Laksh Budhrani | Course Hub'
theme = 're-terminal'

canonifyURLs = true

[params]
  title = "Laksh Budhrani"
  subtitle = "Computer Science Educator"
  mainSections = ["courses"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true